services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: main
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  auth:
    build: ./auth_service
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/main
      SECRET_KEY: example-key
    networks:
      - app_network
    depends_on:
      - postgres

  orders:
    build: ./orders_service
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/main
      AUTH_SERVICE_URL: http://auth:5000/verify
    networks:
      - app_network
    depends_on:
      - postgres
      - auth

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - auth
      - orders

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge